# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StickyNote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StickyNote
  pod 'UIColor_Hex_Swift', '~> 3.0.2'
  pod 'RealmSwift', '~> 3.0.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SmileLock', '~> 2.0.0'
  pod 'VENTouchLock'
  pod 'TOPasscodeViewController'
  pod 'QuickTableViewController'
  pod 'FLEX', '~> 2.2.0'
end
